name: GitHub Pages Deployment

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Hugo
      run: |
        apt-cache policy libstdc++6
        wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_extended_0.55.4_Linux-64bit.deb
        sudo dpkg -i /tmp/hugo.deb

    - name: Build site
      run: hugo || exit 1

    - name: Set up CNAME
      run: echo marian42.de > public/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true
        allow_empty_commit: true
        publish_branch: master
        commit_message: Deploy to Github Pages