name: GitHub Pages Deployment

on:
  push:
    branches:
      - python

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python dependencies
      run: pip install mistune Jinja2 Pillow

    - name: Build site
      run: python generator/main.py || exit 1

    - name: Set up CNAME
      run: echo marian42.de > output/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: master
        full_commit_message: Deploy to Github Pages